### PR TITLE
test-splitter 0.7.2

### PR DESCRIPTION
**Pull request by sj26**
Add https://github.com/buildkite/test-splitter to homebrew so folks can install and use it easily on macOS:

```
brew install buildkite/buildkite/test-splitter
```

### CODE REVIEW

**Comment by wooly** [comment]
If we cut 0.7.1 today/tomorrow, then we can update this to include the `--version` check.

**Comment by sj26** [comment]
@wooly I've updated to 0.7.1 and adjusted to use the version command — thanks for fixing that!

**Comment by wooly** [comment]
@sj26 we're up to 0.7.2 now with a bug in the formatting of output in 0.7.1. Want me to update this and ship it?

**Comment by sj26** [comment]
Please, feel free 🙏

**Comment by wooly** [comment]
Have updated the links and shas for the 0.7.2 version. Is it possible to test these changes before I merge?

**Comment by sj26** [comment]
Yeah, check it installs:

`brew install buildkite/buildkite/test-splitter`

and optionally run the test:

`brew test test-splitter`

**Comment by wooly** [comment]
That wasn't working as I didn't have the tap pointing at this branch, only master.

What I ended up doing was:
```
cd /opt/homebrew/Library/Taps/buildkite/homebrew-buildkite
git checkout add-test-splitter
```

Which then allowed me to install it.

I've also updated the test to match on the version output.

You can revert back to the normal behaviour by doing `brew update-reset $(brew --repo buildkite/homebrew-buildkite)`

**Review by wooly — APPROVED** [review]

**Comment by sj26** [comment]
Thanks @wooly!

Let's put some of that in a doc for future travellers: #35

**Pull request merged**
